resources:
- name: golang
  type: docker-image
  source:
    repository: golang
    tag: 1.13

- name: baseimage
  type: docker-image
  source:
    repository: phusion/baseimage
    tag: latest

- name: cli-ci-base-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli-ci
    branch: master
    paths: [ci/docker-images/dockerfiles/base/Dockerfile]

- name: cli-ci-package-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli-ci
    branch: master
    paths: [ci/docker-images/dockerfiles/package/Dockerfile]

- name: cf-cli-base-image
  type: docker-image
  source:
    repository: cfcli/cli-base
    username: ((dockerhub-username))
    email: ((dockerhub-email))
    password: ((dockerhub-password))

- name: cf-cli-package-image
  type: docker-image
  source:
    repository: cfcli/cli-package
    username: ((dockerhub-username))
    email: ((dockerhub-email))
    password: ((dockerhub-password))

- name: weekly
  type: time
  icon: weather-night
  source:
    location: America/Los_Angeles
    start: 2:00 AM
    stop: 3:00 AM
    days: [Saturday]

jobs:
- name: create-cli-base-image
  serial: true
  plan:
  - in_parallel:
    - get: cli-ci-base-dockerfile
      trigger: true
    - get: golang
      trigger: true
      params: {save: true}
    - get: weekly
      trigger: true
  - put: cf-cli-base-image
    params:
      load_base: golang
      build: cli-ci-base-dockerfile/ci/docker-images/dockerfiles/base

- name: create-cli-package-image
  serial: true
  plan:
  - in_parallel:
    - get: cli-ci-package-dockerfile
      trigger: true
    - get: baseimage
      trigger: true
      params: {save: true}
    - get: weekly
      trigger: true
  - put: cf-cli-package-image
    params:
      load_base: baseimage
      build: cli-ci-base-dockerfile/ci/docker-images/dockerfiles/package
