---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:

- name: cli-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli-ci
    branch: ga-integration

- name: cli
  type: git
  icon: console
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master

- name: cf-ga-binaries
  type: s3
  icon: folder
  source:
    bucket: ((integration-bucket-name))
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: "cf-cli-binaries.tgz"

- name: cf-cli-binaries
  type: s3
  icon: folder
  source:
    bucket: ((staging-bucket-name))
    access_key_id: ((cli-team-aws-s3-access-key-id))
    secret_access_key: ((cli-team-aws-s3-secret-access-key))
    versioned_file: "v8/cf-cli-binaries.tgz"

- name: cf-deployment-concourse-tasks
  type: git
  icon: github-box
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: cf-acceptance-tests-rc
  type: git
  icon: github-box
  source:
    branch: release-candidate
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
    ignore_paths:
    - ci/*.yml
    - .envrc

- name: slack-alert
  type: slack-notification
  icon: slack
  source:
    url: ((slack-webhook-url))

- name: vars-store
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli-private
    private_key: ((cli-private-github-private-key))
    branch: master

- name: ubuntu-64-image
  type: registry-image
  source:
    repository: ubuntu
    tag: latest

- name: ubuntu-32-image
  type: registry-image
  source:
    repository: i386/ubuntu

- name: fedora-image
  type: registry-image
  source:
    repository: fedora

jobs:

- name: prepare-binaries
  serial: true
  plan:
  - in_parallel:
    - get: cli
      trigger: true
      passed: [units]
    - get: cli-ci
  - in_parallel:
    - task: combine-binaries
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/combine-binaries.yml
    - put: cf-cli-binaries
      params:
        file: compiled/cf-cli-binaries.tgz

- name: integration-linux
  serial: true
  plan:
  - in_parallel: &integration_resources
    - get: cli
      passed: [prepare-binaries]
    - get: cli-ci
    - get: cf-cli-binaries
      passed: [prepare-binaries]
      trigger: true
    - get: vars-store
    - put: bosh-lock
      resource: gcp-bosh-pool
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
    - task: integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/integration-linux.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-dev-internal'
          text: &slack_notification_text |
            $BUILD_JOB_NAME failed :(
            $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME - (Viewable internally only)
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
      params: &integration_params
        CF_INT_CLIENT_ID: 'potato-face'
        CF_INT_CLIENT_SECRET: ((client-secret))
        CF_INT_DOCKER_IMAGE: ((dockerhub-private-image))
        CF_INT_DOCKER_USERNAME: ((dockerhub-username))
        CF_INT_DOCKER_PASSWORD: ((dockerhub-password))
        CF_INT_IGNORE_API_VERSION_CHECK: false
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: integration-windows
  serial: true
  plan:
  - in_parallel: *integration_resources
  - do:
    - task: cleanup-integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
    - task: integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/integration-windows.yml
      params:
        <<: *integration_params
      input_mapping:
        cf-credentials: cleanup-integration-outputs
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-dev-internal'
          text: *slack_notification_text
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: integration-linux-client-creds
  serial: true
  plan:
  - in_parallel: *integration_resources
  - do:
    - task: cleanup-integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
    - task: integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/integration-linux.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-dev-internal'
          text: *slack_notification_text
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
      params:
        <<: *integration_params
        CF_INT_CLIENT_CREDENTIALS_TEST_MODE: true
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: integration-windows-client-creds
  serial: true
  plan:
  - in_parallel: *integration_resources
  - do:
    - task: cleanup-integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
    - task: integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/integration-windows.yml
      params:
        <<: *integration_params
        CF_INT_CLIENT_CREDENTIALS_TEST_MODE: true
      input_mapping:
        cf-credentials: cleanup-integration-outputs
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-dev-internal'
          text: *slack_notification_text
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: integration-linux-minimum-capi
  serial: true
  plan:
  - in_parallel: &integration_resources
    - get: cli
      passed: [prepare-binaries]
    - get: cli-ci
    - get: cf-cli-binaries
      passed: [prepare-binaries]
      trigger: true
    - get: vars-store
    - put: bosh-lock
      resource: gcp-bosh-pool-minimum-capi
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
    - task: integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/integration-linux.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-dev-internal'
          text: *slack_notification_text
      ensure:
        task: cleanup-integration
        file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
      params: &integration_params
        CF_INT_CLIENT_ID: 'potato-face'
        CF_INT_CLIENT_SECRET: ((client-secret))
        CF_INT_DOCKER_IMAGE: ((dockerhub-private-image))
        CF_INT_DOCKER_USERNAME: ((dockerhub-username))
        CF_INT_DOCKER_PASSWORD: ((dockerhub-password))
        CF_INT_IGNORE_API_VERSION_CHECK: false
  ensure:
    put: gcp-bosh-pool-minimum-capi
    params:
      release: bosh-lock

- name: cats
  serial: true
  plan:
  - in_parallel:
    - get: cli
      passed:
      - integration-linux
      - integration-linux-client-creds
      - integration-windows
      - integration-windows-client-creds
      - integration-linux-minimum-capi
    - get: cf-acceptance-tests-rc
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: cf-cli-binaries
      passed:
      - integration-linux
      - integration-linux-client-creds
      - integration-windows
      - integration-windows-client-creds
      - integration-linux-minimum-capi
      trigger: true
    - get: cli-ci
    - get: vars-store
    - put: bosh-lock
      resource: gcp-bosh-pool
      timeout: 2h
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
    - task: config
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/cats-config.yml
      params:
        INCLUDE_V3: true
        BROKER_START_TIMEOUT: 330
        CF_PUSH_TIMEOUT: 210
        DEFAULT_TIMEOUT: 60
        LONG_CURL_TIMEOUT: 210
    - task: extract-linux-binary
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/extract-linux-binary.yml
    - task: run-tests
      timeout: 3h
      file: cf-deployment-concourse-tasks/run-cats-with-provided-cli/task.yml
      input_mapping:
        cf-acceptance-tests: cf-acceptance-tests-rc
        integration-config: cats-config
        cf-cli: linux-cf-binary
      params:
        NODES: 16
        SKIP_REGEXP: "transparently proxies both reserved"
        REPORTER_CONFIG_FILE_PATH: ""
        FLAKE_ATTEMPTS: 2
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-dev-internal'
          text: *slack_notification_text
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: cats-minimum-capi
  serial: true
  plan:
  - in_parallel:
    - get: cli
      passed:
      - integration-linux
      - integration-linux-client-creds
      - integration-windows
      - integration-windows-client-creds
      - integration-linux-minimum-capi
    - get: cf-acceptance-tests-rc
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: cf-cli-binaries
      passed:
      - integration-linux
      - integration-linux-client-creds
      - integration-windows
      - integration-windows-client-creds
      - integration-linux-minimum-capi
      trigger: true
    - get: cli-ci
    - get: vars-store
    - put: bosh-lock
      resource: gcp-bosh-pool-minimum-capi
      timeout: 2h
      params:
        acquire: true
  - do:
    - task: cleanup-integration
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/cleanup-integration.yml
    - task: config
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/cats-config.yml
      params:
        INCLUDE_V3: true
        BROKER_START_TIMEOUT: 330
        CF_PUSH_TIMEOUT: 210
        DEFAULT_TIMEOUT: 60
        LONG_CURL_TIMEOUT: 210
    - task: extract-linux-binary
      timeout: 3h
      file: cli-ci/ci/cli-ga-integration/tasks/extract-linux-binary.yml
    - task: run-tests
      timeout: 3h
      file: cf-deployment-concourse-tasks/run-cats-with-provided-cli/task.yml
      input_mapping:
        cf-acceptance-tests: cf-acceptance-tests-rc
        integration-config: cats-config
        cf-cli: linux-cf-binary
      params:
        NODES: 16
        SKIP_REGEXP: "transparently proxies both reserved"
        REPORTER_CONFIG_FILE_PATH: ""
        FLAKE_ATTEMPTS: 2
      on_failure:
        put: slack-alert
        params:
          channel: '#cli-dev-internal'
          text: *slack_notification_text
  ensure:
    put: gcp-bosh-pool-minimum-capi
    params:
      release: bosh-lock

