groups:
- name: workers
  jobs:
  - install-windows-deps-0

jobs:
- name: install-windows-deps-0
  serial: true
  plan:
  - in_parallel:
    - get: cli-ci
  - do:
    - task: install-go-windows-worker-0
      file: cli-ci/ci/concourse/tasks/configure-windows-worker.yml

resources:
- name: cli-ci
  type: git
  icon: &git-icon github
  source:
    uri: https://github.com/cloudfoundry/cli-ci
    branch: master
