---
platform: windows

inputs:
- name: edge-windows-binary-32
- name: edge-windows-binary-64
- name: cli-ci

outputs:
- name: extracted-binaries

params:
  TARGET_V7:

run:
  path: powershell.exe
  args:
  - -command
  - |
    # Print current directory & contents to make debugging easier, for we cannot hijack, but we can `cd`
    Get-ChildItem

    if ($env:TARGET_V7 -eq "true") {
      Set-Variable Suffix "7"
    } else {
      Set-Variable Suffix ""
    }

    Expand-Archive -LiteralPath .\edge-windows-binary-32\cf${Suffix}-cli_edge_win32.zip
    Expand-Archive -LiteralPath .\edge-windows-binary-64\cf${Suffix}-cli_edge_winx64.zip

    & 'C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\signtool.exe' `
      sign `
      /tr http://timestamp.sectigo.com `
      /td sha256 `
      /fd sha256 `
      /n "Cloudfoundry.org Foundation, Inc" `
      .\cf${Suffix}-cli_edge_win32\cf${Suffix}.exe
    Move-Item .\cf${Suffix}-cli_edge_win32\cf${Suffix}.exe .\extracted-binaries\cf${Suffix}-cli_win32.exe

    & 'C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\signtool.exe' `
      sign `
      /tr http://timestamp.sectigo.com `
      /td sha256 `
      /fd sha256 `
      /n "Cloudfoundry.org Foundation, Inc" `
      .\cf${Suffix}-cli_edge_winx64\cf${Suffix}.exe
    Move-Item .\cf${Suffix}-cli_edge_winx64\cf${Suffix}.exe .\extracted-binaries\cf${Suffix}-cli_winx64.exe
