---
platform: darwin

params:
  CERT_COMMON_NAME:
  CERT_LOCATION:
  CERT_PASSWORD_LOCATION:
  TARGET_V7:

inputs:
- name: certificates
- name: cli
- name: edge-osx-installer-64

outputs:
- name: signed-osx-installer

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    if [ "$TARGET_V7" == "true" ]; then
      VERSION=$(cat cli/BUILD_VERSION_V7)
      SUFFIX="7"
    else
      VERSION=$(cat cli/BUILD_VERSION)
      SUFFIX=""
    fi

    CERT_PASSWORD=$(cat certificates/$CERT_PASSWORD_LOCATION)

    security create-keychain -p "" temp-keychain

    trap "security delete-keychain temp-keychain" 0

    security import certificates/$CERT_LOCATION -k temp-keychain -T "$(which productsign)" -P "$CERT_PASSWORD"

    productsign --timestamp \
      --sign "$CERT_COMMON_NAME" \
      --keychain temp-keychain \
      edge-osx-installer-64/cf${SUFFIX}-cli-installer_edge_osx.pkg \
      signed-osx-installer/cf${SUFFIX}-cli-installer_${VERSION}_osx.pkg
