---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

inputs:
- name: cli
- name: homebrew-tap

outputs:
- name: update-brew-formula-output

params:
  OUTPUT_PATH: update-brew-formula-output

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    VERSION=$(cat cli/BUILD_VERSION_V7)

    mkdir cf7-cli-osx-tarball cf7-cli-linux-tarball
    curl -L "https://packages.cloudfoundry.org/stable?release=macosx64-binary&version=${VERSION}&source=github-rel" > cf7-cli-osx-tarball/cf7-cli_${VERSION}_osx.tgz
    curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${VERSION}&source=github-rel" > cf7-cli-linux-tarball/cf7-cli_${VERSION}_linux64.tgz

    pushd cf7-cli-osx-tarball
      CLI_OSX_SHA256=$(shasum -a 256 cf7-cli_*_osx.tgz | cut -d ' ' -f 1)
    popd

    pushd cf7-cli-linux-tarball
      CLI_LINUX_64_SHA256=$(shasum -a 256 cf7-cli_*_linux64.tgz | cut -d ' ' -f 1)
    popd

    pushd homebrew-tap
      cat <<EOF > cf7-cli.rb
    require 'formula'

    class Cf7Cli < Formula
      homepage 'https://code.cloudfoundry.org/cli'
      version '${VERSION}'

      if OS.mac?
        url 'https://packages.cloudfoundry.org/homebrew/cf7-${VERSION}.tgz'
        sha256 '${CLI_OSX_SHA256}'
      elsif OS.linux?
        url 'https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${VERSION}&source=homebrew'
        sha256 '${CLI_LINUX_64_SHA256}'
      end

      depends_on :arch => :x86_64

      def install
        bin.install 'cf7'
        (bash_completion/"cf7-cli").write <<-completion
    $(cat ../cli/ci/installers/completion/cf7)
        completion
        doc.install 'LICENSE'
        doc.install 'NOTICE'
      end

      test do
        system "#{bin}/cf7"
      end
    end
    EOF

    git add cf7-cli.rb
    if ! [ -z "$(git status --porcelain)"];
    then
      git config --global user.email "cf-cli-eng@pivotal.io"
      git config --global user.name "Concourse CI"
      git commit -m "Release ${VERSION}"
    else
        echo "no new version to commit"
    fi
    cat cf7-cli.rb
    popd

    cp -R homebrew-tap $OUTPUT_PATH

