---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  TARGET_MAJOR_VERSION:

inputs:
- name: cli
- name: repackaged-binaries-and-installers
- name: signed-osx-installer
- name: signed-redhat-installer
- name: signed-windows-zips

outputs:
- name: cf-cli-osx-tarball

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    if [ "$TARGET_MAJOR_VERSION" == "7" ]; then
      VERSION=$(cat cli/BUILD_VERSION)
      BUCKET_PREFIX=v7-
    elif [ "$TARGET_MAJOR_VERSION" == "8" ]; then
      VERSION=$(cat cli/BUILD_VERSION)
      BUCKET_PREFIX=v8-
    else
      VERSION=$(cat cli/BUILD_VERSION)
      BUCKET_PREFIX=
    fi

    aws s3 cp repackaged-binaries-and-installers/ s3://${BUCKET_PREFIX}cf-cli-releases/releases/v${VERSION}/ --recursive
    aws s3 cp signed-osx-installer/ s3://${BUCKET_PREFIX}cf-cli-releases/releases/v${VERSION}/ --recursive
    aws s3 cp signed-redhat-installer/ s3://${BUCKET_PREFIX}cf-cli-releases/releases/v${VERSION}/ --recursive
    aws s3 cp signed-windows-zips/ s3://${BUCKET_PREFIX}cf-cli-releases/releases/v${VERSION}/ --recursive
