---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-package

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  TARGET_V7:
  OPTIONAL_AWS_DEV_BUCKET:

inputs:
- name: cli
- name: repackaged-binaries-and-installers
- name: signed-osx-installer
- name: signed-redhat-installer
- name: signed-windows-zips

outputs:
- name: cf-cli-osx-tarball

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    if [ "$TARGET_V7" == "true" ]; then
      VERSION=$(cat cli/BUILD_VERSION)
      VERSION_PREFIX=v7-
    else
      VERSION=$(cat cli/BUILD_VERSION)
      VERSION_PREFIX=
    fi

    AWS_FULL_PATH=s3://${OPTIONAL_AWS_DEV_BUCKET}${VERSION_PREFIX}cf-cli-releases/releases/v${VERSION}/
    aws s3 cp repackaged-binaries-and-installers/ ${AWS_FULL_PATH} --recursive
    aws s3 cp signed-osx-installer/ ${AWS_FULL_PATH} --recursive
    aws s3 cp signed-redhat-installer/ ${AWS_FULL_PATH} --recursive
    aws s3 cp signed-windows-zips/ ${AWS_FULL_PATH} --recursive
