---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli-plugin-repo
  path: gopath/src/code.cloudfoundry.org/cli-plugin-repo

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH

    go get github.com/onsi/ginkgo/ginkgo

    cd $GOPATH/src/code.cloudfoundry.org/cli-plugin-repo

    BINARY_VALIDATION=false bin/test
