---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: gcp-env

run:
  path: bash
  args:
  - -c
  - |
    set -e

    ENV=$(cat gcp-env/name)
    cat gcp-env/metadata > $ENV.json
    eval "$(bbl print-env --metadata-file $ENV.json)"
    bosh -d cf delete-deployment -n
    