---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli
- name: cf-cli-binaries
- name: gcp-env
- name: cli-ci
- name: cf-deployment

params:
  CF_CLI_EXPERIMENTAL: false
  # CF_INT_CLIENT_ID:
  # CF_INT_CLIENT_SECRET:
  # CF_INT_DOCKER_IMAGE:
  # CF_INT_DOCKER_USERNAME:
  # CF_INT_DOCKER_PASSWORD:
  # CF_INT_IGNORE_API_VERSION_CHECK:
  FLAKE_ATTEMPTS: 2
  NODES: 16

run:
  path: bash
  args:
  - -c
  - |
    set -e

    export GOFLAGS="-mod=mod"
    mkdir -p go/src/code.cloudfoundry.org
    ln -s ${PWD}/cli go/src/code.cloudfoundry.org
    ENV=$(cat gcp-env/name)
    export SSL_CERT_DIR=/tmp/cert_dir
    mkdir -p $SSL_CERT_DIR

    cat gcp-env/metadata > $ENV.json

    eval "$(bbl print-env --metadata-file $ENV.json)"

    credhub login
    export CF_INT_PASSWORD=$(credhub get -n /bosh-$ENV/cf/cf_admin_password | bosh interpolate --path /value -)
    export CF_INT_OIDC_USERNAME="admin-oidc"
    export CF_INT_OIDC_PASSWORD=$(credhub get -n /bosh-$ENV/cf/uaa_oidc_admin_password | bosh interpolate --path /value -)

    credhub get --name /bosh-$ENV/cf/router_ca | bosh interpolate - --path /value/certificate > $SSL_CERT_DIR/$ENV.router.ca

    echo "Deployed CAPI version:"
    bosh -d cf releases | grep capi

    # Enable SSL Validation once toolsmiths supports it
    # export SKIP_SSL_VALIDATION=false

    set -x

    export CF_INT_API="https://api.${ENV}.cf-app.com"
    export CF_DIAL_TIMEOUT=15
    export CF_USERNAME=admin

    export GOPATH=$PWD/go
    export PATH=$GOPATH/bin:$PATH

    pushd cf-cli-binaries
      tar xvzf cf-cli-binaries.tgz
      chmod +x cf-cli_linux_x86-64
      mkdir -p $GOPATH/bin
      mv cf-cli_linux_x86-64 $GOPATH/bin/cf
    popd

    if [[ $CF_INT_CLIENT_CREDENTIALS_TEST_MODE != "true" ]]; then
      CF_INT_CLIENT_ID=""
      CF_INT_CLIENT_SECRET=""
    fi

    cd $GOPATH/src/code.cloudfoundry.org/cli
    go install github.com/onsi/ginkgo/ginkgo@v1.16.4

    export CF_PASSWORD=${CF_INT_PASSWORD}
    cf api ${CF_INT_API} --skip-ssl-validation
    cf auth
    cf enable-feature-flag route_sharing
    make integration-tests-full-ci
