---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: cli-ci
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/cli-ci

  - name: slack-alert
    type: slack-notification
    icon: slack
    source:
      url: ((vat-slack-webhook-url))

  - name: end-of-work-day
    type: time
    icon: weather-night
    source:
      location: America/Los_Angeles
      start: 6:00 PM
      stop: 6:15 PM
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]

jobs:
  - name: alert-and-wait
    plan:
      - get: end-of-work-day
        trigger: true
      - put: slack-alert
        params:
          channel: '#cli-eng'
          text: >
            [THIS IS A TEST OF THE PUBLIC BROADCASTING SYSTEM] Hi team! Your cloud workstations will automatically shut down in 20 minutes. If you're still working,
            pause the shutdown job for your workstation to prevent this! :josh-sleuth:
      - task: wait-20-minutes
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: busybox
          run:
            path: sh
            args:
              - -c
              - |
                sleep 1200

  - name: shutdown-cli-ws-1
    plan:
      - get: cli-ci
      - get: end-of-work-day
        trigger: true
        passed: [alert-and-wait]
      - task: shutdown
        file: cli-ci/ci/workstation-scheduler/tasks/shutdown-ws.yml
        params:
          GCP_VM_NAME: cli-ws-1
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((workstation-scheduler-gcp-json-key))

  - name: shutdown-cli-ws-2
    plan:
      - get: cli-ci
      - get: end-of-work-day
        trigger: true
        passed: [alert-and-wait]
      - task: shutdown
        file: cli-ci/ci/workstation-scheduler/tasks/shutdown-ws.yml
        params:
          GCP_VM_NAME: cli-ws-2
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((workstation-scheduler-gcp-json-key))

  - name: shutdown-cli-ws-3
    plan:
      - get: cli-ci
      - get: end-of-work-day
        trigger: true
        passed: [alert-and-wait]
      - task: shutdown
        file: cli-ci/ci/workstation-scheduler/tasks/shutdown-ws.yml
        params:
          GCP_VM_NAME: cli-ws-3
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((workstation-scheduler-gcp-json-key))

  - name: shutdown-cli-ws-4
    plan:
      - get: cli-ci
      - get: end-of-work-day
        trigger: true
        passed: [alert-and-wait]
      - task: shutdown
        file: cli-ci/ci/workstation-scheduler/tasks/shutdown-ws.yml
        params:
          GCP_VM_NAME: cli-ws-4
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((workstation-scheduler-gcp-json-key))

