---
resources:
  - name: cli-ci
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/cli-ci

  - name: end-of-work-day
    type: time
    icon: weather-night
    source:
      location: America/Los_Angeles
      start: 6:30 PM
      stop: 7:00 PM
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]

jobs:
  - name: shutdown-cli-ws-1
    plan:
      - get: cli-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: cli-ci/ci/workstation-scheduler/tasks/shutdown-ws.yml
        params:
          GCP_VM_NAME: cli-ws-1
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((workstation-scheduler-gcp-json-key))

  - name: shutdown-cli-ws-2
    plan:
      - get: cli-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: cli-ci/ci/workstation-scheduler/tasks/shutdown-ws.yml
        params:
          GCP_VM_NAME: cli-ws-2
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((workstation-scheduler-gcp-json-key))

  - name: shutdown-cli-ws-3
    plan:
      - get: cli-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: cli-ci/ci/workstation-scheduler/tasks/shutdown-ws.yml
        params:
          GCP_VM_NAME: cli-ws-3
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((workstation-scheduler-gcp-json-key))

  - name: shutdown-cli-ws-4
    plan:
      - get: cli-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: cli-ci/ci/workstation-scheduler/tasks/shutdown-ws.yml
        params:
          GCP_VM_NAME: cli-ws-4
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((workstation-scheduler-gcp-json-key))

