---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk

params:
  GCP_VM_NAME: ""
  GCP_PROJECT_NAME: "cf-cli"
  GCP_SERVICE_ACCOUNT_KEY: ""

run:
  path: bash
  args:
    - -c
    - |
      set -e

      gcloud auth activate-service-account --key-file=<(echo $GCP_SERVICE_ACCOUNT_KEY)

      echo "Shutting down VM $GCP_VM_NAME in project $GCP_PROJECT_NAME..."

      gcloud compute instances stop $GCP_VM_NAME --project $GCP_PROJECT_NAME
