#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"resources": []})
---
resources:
#@overlay/match by=overlay.subset({"source":{"prefix":"cf-cli-releases"}}), expects='1+'
- source:
    bucket: cf-cli-releases
    region_name: us-west-1
    #@overlay/remove
    prefix:
#@overlay/match by=overlay.subset({"source":{"prefix":"v7-cf-cli-releases"}}), expects='1+'
- source:
    bucket: v7-cf-cli-releases
    region_name: us-west-1
    #@overlay/remove
    prefix:

#@overlay/match by=overlay.all, expects="0+"
---
jobs:
#@overlay/match by="name"
- name: update-debian-repo-v6
  plan:
  #@overlay/match by=overlay.subset({"task":"publish-debian"})
  - task: publish-debian
    params:
      AWS_BUCKET_NAME: cf-cli-debian-repo
      CLAW_URL: ((claw-url))
      #@overlay/remove
      AWS_PREFIX_FLAG:

#@overlay/match by="name"
- name: update-debian-repo-v7
  plan:
  #@overlay/match by=overlay.subset({"task":"publish-debian"})
  - task: publish-debian
    params:
      AWS_BUCKET_NAME: cf-cli-debian-repo
      CLAW_URL: ((claw-url))
      #@overlay/remove
      AWS_PREFIX_FLAG:

#@overlay/match by="name"
- name: update-rpm-repo-v6
  plan:
  #@overlay/match by=overlay.subset({"task":"publish-rpm"})
  - task: publish-rpm
    params:
      AWS_RELEASES_PATH: cf-cli-releases
      AWS_RELEASES_PATH_V7: v7-cf-cli-releases
      AWS_RPM_PATH: cf-cli-rpm-repo

#@overlay/match by="name"
- name: update-rpm-repo-v7
  plan:
  #@overlay/match by=overlay.subset({"task":"publish-rpm"})
  - task: publish-rpm
    params:
      AWS_RELEASES_PATH: cf-cli-releases
      AWS_RELEASES_PATH_V7: v7-cf-cli-releases
      AWS_RPM_PATH: cf-cli-rpm-repo

#@overlay/match by="name"
- name: update-homebrew-v6
  plan:
  #@overlay/match by=overlay.subset({"task":"update-brew-formula"})
  - task: update-brew-formula
    params:
      CLAW_URL: ((claw_url))
      #@overlay/remove
      DEV_SUFFIX:

#@overlay/match by="name"
- name: update-homebrew-v7
  plan:
  #@overlay/match by=overlay.subset({"task":"update-brew-formula"})
  - task: update-brew-formula
    params:
      CLAW_URL: ((claw_url))
      #@overlay/remove
      DEV_SUFFIX:

#@overlay/match by="name"
- name: create-and-sign-installers-v6
  plan:
  #@overlay/match by=overlay.subset({"task":"upload-releases"})
  - task: upload-releases
    params:
      #@overlay/remove
      OPTIONAL_AWS_DEV_BUCKET:
