platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: bbl-state

run:
  path: bash
  args:
    - -c
    - |
      set -eu

      function setup_bosh_env_vars() {
        pushd "bbl-state/${BBL_STATE_DIR}"
          eval "$(bbl print-env)"
        popd
      }

      function upload_stemcell() {
        bosh upload-stemcell --sha2 https://bosh.io/d/stemcells/bosh-google-kvm-windows2019-go_agent
      }

      function main() {
        setup_bosh_env_vars
        upload_stemcell
      }

      main

params:
  BBL_STATE_DIR:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - If unspecified, uses the root of the `bbl-state` input
