platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli
  path: gopath/src/code.cloudfoundry.org/cli
- name: i18n-data

outputs:
- name: linux-compiled

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cwd=$PWD

    export GOPATH=$PWD/gopath
    export PATH=$GOPATH/bin:$PATH
    export TARGET_GO_VERSION=${TARGET_GO_VERSION:-"UNSET"}

    if go version | grep -v "\b$TARGET_GO_VERSION\b"; then
      echo "ERROR: expected target go version [ $TARGET_GO_VERSION ]"
      exit 1
    fi

    go version

    mv i18n-data/i18n_resources.go $GOPATH/src/code.cloudfoundry.org/cli/i18n/resources

    pushd $GOPATH/src/code.cloudfoundry.org/cli
      export CF_BUILD_VERSION=$(cat BUILD_VERSION)
      export CF_BUILD_SHA=$(git rev-parse --short HEAD)
      export CF_BUILD_DATE=$(date -u +"%Y-%m-%d")

      echo "Building 32-bit Linux"
      make out/cf7-cli_linux_i686

      echo "Building 64-bit Linux"
      make out/cf7-cli_linux_x86-64

      echo "Building 32-bit Windows"
      make out/cf7-cli_win32.exe

      echo "Building 64-bit Windows"
      make out/cf7-cli_winx64.exe

      echo "Creating tarball"
      tar -cvzf $cwd/linux-compiled/cf-cli-binaries.tgz -C out .
    popd
