---
platform: windows

inputs:
- name: extracted-binaries
- name: cli
- name: cli-ci

outputs:
- name: winstallers

run:
  path: powershell
  args:
  - cli-ci/ci/cli-v7/tasks/create-installers-windows.ps1
