---
platform: windows

inputs:
- name: cli
- name: cf-cli-binaries
- name: bosh-lock
- name: cf-credentials

params:
  CF_INT_CLIENT_ID:
  CF_INT_CLIENT_SECRET:
  CF_INT_DOCKER_IMAGE:
  CF_INT_DOCKER_USERNAME:
  CF_INT_DOCKER_PASSWORD:

run:
  path: cli/ci/cli/tasks/integration-experimental-windows.bat
