platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-cli
    tag: latest

inputs:
  - name: capi-ci
  - name: director-state

run:
  path: capi-ci/ci/bosh-lite/delete-bosh-lite.sh