---
resources:
- name: cli
  type: git
  icon: console
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: v7

- name: cli-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli-ci
    branch: docker-image-cli

- name: cf-cli-push
  type: registry-image
  icon: docker
  source:
    repository: cfcli/cf-cli-test
    username: ((username))
    password: ((password))

jobs:
- name: docker-image-cli-v7
  plan:
  - in_parallel:
    - get: cli
    - get: cli-ci
  - task: build-image
    privileged: true
    config:
      run:
        path: "build"
      platform: linux

      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task

      inputs:
      - name: cli
        path: .

      outputs:
      - name: image

      params:
        CONTEXT: docker
        UNPACK_ROOTFS: true
  - task: test-image
    image: image
    file: cli-ci/ci/shared/tasks/test-docker-image.yml
    params:
      VERSION: 7
  - put: cf-cli-push
    params: {image: image/image.tar}
