---
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/cf-custom?
  value:
    access-token-validity: 120
    authorities: uaa.none
    authorized-grant-types: password,refresh_token
    override: true
    refresh-token-validity: 2592000
    scope: network.admin,network.write,cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write,doppler.firehose,uaa.user,routing.router_groups.read,routing.router_groups.write,cloud_controller.admin_read_only,cloud_controller.global_auditor,perm.admin,clients.read
    secret: ((custom-client-secret))

- type: replace
  path: /variables?/-
  value:
    name: custom-client-secret
    type: password
