platform: linux
inputs:
- name: cli
params:
  VERSION:
run:
  path: sh
  args:
  - -c
  - |
      set -eux

      if ! [ -x "$(command -v cf)" ]; then
        echo 'Error: cf is not installed.' >&2
        exit 1
      fi

      CF_VERSION="$(cf -v)"

      if [[ ! "${CF_VERSION}" == *"cf version $VERSION"* ]]; then
        echo "Error: cf -v did not match expected version"
        echo "Expected: $VERSION"
        echo "Got ${CF_VERSION}"
        exit 1
      fi
