---
platform: windows

inputs:
- name: cli
  path: go/src/code.cloudfoundry.org/cli
- name: cf-cli-binaries
- name: bosh-lock
- name: cli-ci
- name: cf-credentials

params:
  CF_INT_CLIENT_ID:
  CF_INT_CLIENT_SECRET:
  CF_INT_CLIENT_CREDENTIALS_TEST_MODE: false
  CF_INT_DOCKER_IMAGE:
  CF_INT_DOCKER_USERNAME:
  CF_INT_DOCKER_PASSWORD:
  CF_INT_IGNORE_API_VERSION_CHECK: false

run:
  path: powershell
  args:
  - cli-ci/ci/cli/tasks/integration-experimental-windows.ps1
